/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.form_di_segnalazione.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the form_di_segnalazione service. Represents a row in the &quot;form_di_segnalazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.daffo.form_di_segnalazione.model.impl.form_di_segnalazioneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.daffo.form_di_segnalazione.model.impl.form_di_segnalazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see form_di_segnalazione
 * @see com.daffo.form_di_segnalazione.model.impl.form_di_segnalazioneImpl
 * @see com.daffo.form_di_segnalazione.model.impl.form_di_segnalazioneModelImpl
 * @generated
 */
public interface form_di_segnalazioneModel extends BaseModel<form_di_segnalazione> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form_di_segnalazione model instance should use the {@link form_di_segnalazione} interface instead.
	 */

	/**
	 * Returns the primary key of this form_di_segnalazione.
	 *
	 * @return the primary key of this form_di_segnalazione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form_di_segnalazione.
	 *
	 * @param primaryKey the primary key of this form_di_segnalazione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the form_di_segnalazione_id of this form_di_segnalazione.
	 *
	 * @return the form_di_segnalazione_id of this form_di_segnalazione
	 */
	public long getForm_di_segnalazione_id();

	/**
	 * Sets the form_di_segnalazione_id of this form_di_segnalazione.
	 *
	 * @param Form_di_segnalazione_id the form_di_segnalazione_id of this form_di_segnalazione
	 */
	public void setForm_di_segnalazione_id(long Form_di_segnalazione_id);

	/**
	 * Returns the c o d i c e of this form_di_segnalazione.
	 *
	 * @return the c o d i c e of this form_di_segnalazione
	 */
	@AutoEscape
	public String getCODICE();

	/**
	 * Sets the c o d i c e of this form_di_segnalazione.
	 *
	 * @param CODICE the c o d i c e of this form_di_segnalazione
	 */
	public void setCODICE(String CODICE);

	/**
	 * Returns the i n i z i a l i_1 of this form_di_segnalazione.
	 *
	 * @return the i n i z i a l i_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINIZIALI_1();

	/**
	 * Sets the i n i z i a l i_1 of this form_di_segnalazione.
	 *
	 * @param INIZIALI_1 the i n i z i a l i_1 of this form_di_segnalazione
	 */
	public void setINIZIALI_1(String INIZIALI_1);

	/**
	 * Returns the i n i z i a l i_1_a of this form_di_segnalazione.
	 *
	 * @return the i n i z i a l i_1_a of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINIZIALI_1_a();

	/**
	 * Sets the i n i z i a l i_1_a of this form_di_segnalazione.
	 *
	 * @param INIZIALI_1_a the i n i z i a l i_1_a of this form_di_segnalazione
	 */
	public void setINIZIALI_1_a(String INIZIALI_1_a);

	/**
	 * Returns the i n i z i a l i_1_b of this form_di_segnalazione.
	 *
	 * @return the i n i z i a l i_1_b of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINIZIALI_1_b();

	/**
	 * Sets the i n i z i a l i_1_b of this form_di_segnalazione.
	 *
	 * @param INIZIALI_1_b the i n i z i a l i_1_b of this form_di_segnalazione
	 */
	public void setINIZIALI_1_b(String INIZIALI_1_b);

	/**
	 * Returns the i n i z i a l i_1_c of this form_di_segnalazione.
	 *
	 * @return the i n i z i a l i_1_c of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINIZIALI_1_c();

	/**
	 * Sets the i n i z i a l i_1_c of this form_di_segnalazione.
	 *
	 * @param INIZIALI_1_c the i n i z i a l i_1_c of this form_di_segnalazione
	 */
	public void setINIZIALI_1_c(String INIZIALI_1_c);

	/**
	 * Returns the i n i z i a l i_1_d of this form_di_segnalazione.
	 *
	 * @return the i n i z i a l i_1_d of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINIZIALI_1_d();

	/**
	 * Sets the i n i z i a l i_1_d of this form_di_segnalazione.
	 *
	 * @param INIZIALI_1_d the i n i z i a l i_1_d of this form_di_segnalazione
	 */
	public void setINIZIALI_1_d(String INIZIALI_1_d);

	/**
	 * Returns the i n i z i a l i_1_e of this form_di_segnalazione.
	 *
	 * @return the i n i z i a l i_1_e of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINIZIALI_1_e();

	/**
	 * Sets the i n i z i a l i_1_e of this form_di_segnalazione.
	 *
	 * @param INIZIALI_1_e the i n i z i a l i_1_e of this form_di_segnalazione
	 */
	public void setINIZIALI_1_e(String INIZIALI_1_e);

	/**
	 * Returns the d a t a_2 of this form_di_segnalazione.
	 *
	 * @return the d a t a_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDATA_2();

	/**
	 * Sets the d a t a_2 of this form_di_segnalazione.
	 *
	 * @param DATA_2 the d a t a_2 of this form_di_segnalazione
	 */
	public void setDATA_2(String DATA_2);

	/**
	 * Returns the s e s s o_3 of this form_di_segnalazione.
	 *
	 * @return the s e s s o_3 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getSESSO_3();

	/**
	 * Sets the s e s s o_3 of this form_di_segnalazione.
	 *
	 * @param SESSO_3 the s e s s o_3 of this form_di_segnalazione
	 */
	public void setSESSO_3(String SESSO_3);

	/**
	 * Returns the d a t a_4 of this form_di_segnalazione.
	 *
	 * @return the d a t a_4 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDATA_4();

	/**
	 * Sets the d a t a_4 of this form_di_segnalazione.
	 *
	 * @param DATA_4 the d a t a_4 of this form_di_segnalazione
	 */
	public void setDATA_4(String DATA_4);

	/**
	 * Returns the o r i g i n e_5 of this form_di_segnalazione.
	 *
	 * @return the o r i g i n e_5 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getORIGINE_5();

	/**
	 * Sets the o r i g i n e_5 of this form_di_segnalazione.
	 *
	 * @param ORIGINE_5 the o r i g i n e_5 of this form_di_segnalazione
	 */
	public void setORIGINE_5(String ORIGINE_5);

	/**
	 * Returns the d e s c r i z i o n e_6 of this form_di_segnalazione.
	 *
	 * @return the d e s c r i z i o n e_6 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDESCRIZIONE_6();

	/**
	 * Sets the d e s c r i z i o n e_6 of this form_di_segnalazione.
	 *
	 * @param DESCRIZIONE_6 the d e s c r i z i o n e_6 of this form_di_segnalazione
	 */
	public void setDESCRIZIONE_6(String DESCRIZIONE_6);

	/**
	 * Returns the i n d i c a r e_7_1 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_7_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_7_1();

	/**
	 * Sets the i n d i c a r e_7_1 of this form_di_segnalazione.
	 *
	 * @param INDICARE_7_1 the i n d i c a r e_7_1 of this form_di_segnalazione
	 */
	public void setINDICARE_7_1(String INDICARE_7_1);

	/**
	 * Returns the i n d i c a r e_7_2 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_7_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_7_2();

	/**
	 * Sets the i n d i c a r e_7_2 of this form_di_segnalazione.
	 *
	 * @param INDICARE_7_2 the i n d i c a r e_7_2 of this form_di_segnalazione
	 */
	public void setINDICARE_7_2(String INDICARE_7_2);

	/**
	 * Returns the i n d i c a r e_7_3 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_7_3 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_7_3();

	/**
	 * Sets the i n d i c a r e_7_3 of this form_di_segnalazione.
	 *
	 * @param INDICARE_7_3 the i n d i c a r e_7_3 of this form_di_segnalazione
	 */
	public void setINDICARE_7_3(String INDICARE_7_3);

	/**
	 * Returns the i n d i c a r e_7_4 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_7_4 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_7_4();

	/**
	 * Sets the i n d i c a r e_7_4 of this form_di_segnalazione.
	 *
	 * @param INDICARE_7_4 the i n d i c a r e_7_4 of this form_di_segnalazione
	 */
	public void setINDICARE_7_4(String INDICARE_7_4);

	/**
	 * Returns the i n d i c a r e_7_5 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_7_5 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_7_5();

	/**
	 * Sets the i n d i c a r e_7_5 of this form_di_segnalazione.
	 *
	 * @param INDICARE_7_5 the i n d i c a r e_7_5 of this form_di_segnalazione
	 */
	public void setINDICARE_7_5(String INDICARE_7_5);

	/**
	 * Returns the i n d i c a r e_7_6 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_7_6 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_7_6();

	/**
	 * Sets the i n d i c a r e_7_6 of this form_di_segnalazione.
	 *
	 * @param INDICARE_7_6 the i n d i c a r e_7_6 of this form_di_segnalazione
	 */
	public void setINDICARE_7_6(String INDICARE_7_6);

	/**
	 * Returns the i n d i c a r e_7_7 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_7_7 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_7_7();

	/**
	 * Sets the i n d i c a r e_7_7 of this form_di_segnalazione.
	 *
	 * @param INDICARE_7_7 the i n d i c a r e_7_7 of this form_di_segnalazione
	 */
	public void setINDICARE_7_7(String INDICARE_7_7);

	/**
	 * Returns the g r a v i t a_8_1 of this form_di_segnalazione.
	 *
	 * @return the g r a v i t a_8_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getGRAVITA_8_1();

	/**
	 * Sets the g r a v i t a_8_1 of this form_di_segnalazione.
	 *
	 * @param GRAVITA_8_1 the g r a v i t a_8_1 of this form_di_segnalazione
	 */
	public void setGRAVITA_8_1(String GRAVITA_8_1);

	/**
	 * Returns the g r a v i t a_8_2 of this form_di_segnalazione.
	 *
	 * @return the g r a v i t a_8_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getGRAVITA_8_2();

	/**
	 * Sets the g r a v i t a_8_2 of this form_di_segnalazione.
	 *
	 * @param GRAVITA_8_2 the g r a v i t a_8_2 of this form_di_segnalazione
	 */
	public void setGRAVITA_8_2(String GRAVITA_8_2);

	/**
	 * Returns the g r a v i t a_8_3 of this form_di_segnalazione.
	 *
	 * @return the g r a v i t a_8_3 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getGRAVITA_8_3();

	/**
	 * Sets the g r a v i t a_8_3 of this form_di_segnalazione.
	 *
	 * @param GRAVITA_8_3 the g r a v i t a_8_3 of this form_di_segnalazione
	 */
	public void setGRAVITA_8_3(String GRAVITA_8_3);

	/**
	 * Returns the g r a v i t a_8_4 of this form_di_segnalazione.
	 *
	 * @return the g r a v i t a_8_4 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getGRAVITA_8_4();

	/**
	 * Sets the g r a v i t a_8_4 of this form_di_segnalazione.
	 *
	 * @param GRAVITA_8_4 the g r a v i t a_8_4 of this form_di_segnalazione
	 */
	public void setGRAVITA_8_4(String GRAVITA_8_4);

	/**
	 * Returns the g r a v i t a_8_5 of this form_di_segnalazione.
	 *
	 * @return the g r a v i t a_8_5 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getGRAVITA_8_5();

	/**
	 * Sets the g r a v i t a_8_5 of this form_di_segnalazione.
	 *
	 * @param GRAVITA_8_5 the g r a v i t a_8_5 of this form_di_segnalazione
	 */
	public void setGRAVITA_8_5(String GRAVITA_8_5);

	/**
	 * Returns the g r a v i t a_8_6 of this form_di_segnalazione.
	 *
	 * @return the g r a v i t a_8_6 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getGRAVITA_8_6();

	/**
	 * Sets the g r a v i t a_8_6 of this form_di_segnalazione.
	 *
	 * @param GRAVITA_8_6 the g r a v i t a_8_6 of this form_di_segnalazione
	 */
	public void setGRAVITA_8_6(String GRAVITA_8_6);

	/**
	 * Returns the g r a v i t a_8_7 of this form_di_segnalazione.
	 *
	 * @return the g r a v i t a_8_7 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getGRAVITA_8_7();

	/**
	 * Sets the g r a v i t a_8_7 of this form_di_segnalazione.
	 *
	 * @param GRAVITA_8_7 the g r a v i t a_8_7 of this form_di_segnalazione
	 */
	public void setGRAVITA_8_7(String GRAVITA_8_7);

	/**
	 * Returns the e v e n t u a l i_9 of this form_di_segnalazione.
	 *
	 * @return the e v e n t u a l i_9 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getEVENTUALI_9();

	/**
	 * Sets the e v e n t u a l i_9 of this form_di_segnalazione.
	 *
	 * @param EVENTUALI_9 the e v e n t u a l i_9 of this form_di_segnalazione
	 */
	public void setEVENTUALI_9(String EVENTUALI_9);

	/**
	 * Returns the e s i t o_10 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10();

	/**
	 * Sets the e s i t o_10 of this form_di_segnalazione.
	 *
	 * @param ESITO_10 the e s i t o_10 of this form_di_segnalazione
	 */
	public void setESITO_10(String ESITO_10);

	/**
	 * Returns the e s i t o_10_1 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_1();

	/**
	 * Sets the e s i t o_10_1 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_1 the e s i t o_10_1 of this form_di_segnalazione
	 */
	public void setESITO_10_1(String ESITO_10_1);

	/**
	 * Returns the e s i t o_10_2 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_2();

	/**
	 * Sets the e s i t o_10_2 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_2 the e s i t o_10_2 of this form_di_segnalazione
	 */
	public void setESITO_10_2(String ESITO_10_2);

	/**
	 * Returns the e s i t o_10_3 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_3 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_3();

	/**
	 * Sets the e s i t o_10_3 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_3 the e s i t o_10_3 of this form_di_segnalazione
	 */
	public void setESITO_10_3(String ESITO_10_3);

	/**
	 * Returns the e s i t o_10_4 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_4 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_4();

	/**
	 * Sets the e s i t o_10_4 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_4 the e s i t o_10_4 of this form_di_segnalazione
	 */
	public void setESITO_10_4(String ESITO_10_4);

	/**
	 * Returns the e s i t o_10_5 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_5 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_5();

	/**
	 * Sets the e s i t o_10_5 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_5 the e s i t o_10_5 of this form_di_segnalazione
	 */
	public void setESITO_10_5(String ESITO_10_5);

	/**
	 * Returns the e s i t o_10_6 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_6 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_6();

	/**
	 * Sets the e s i t o_10_6 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_6 the e s i t o_10_6 of this form_di_segnalazione
	 */
	public void setESITO_10_6(String ESITO_10_6);

	/**
	 * Returns the e s i t o_10_7 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_7 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_7();

	/**
	 * Sets the e s i t o_10_7 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_7 the e s i t o_10_7 of this form_di_segnalazione
	 */
	public void setESITO_10_7(String ESITO_10_7);

	/**
	 * Returns the e s i t o_10_8 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_8 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_8();

	/**
	 * Sets the e s i t o_10_8 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_8 the e s i t o_10_8 of this form_di_segnalazione
	 */
	public void setESITO_10_8(String ESITO_10_8);

	/**
	 * Returns the e s i t o_10_9 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_9 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_9();

	/**
	 * Sets the e s i t o_10_9 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_9 the e s i t o_10_9 of this form_di_segnalazione
	 */
	public void setESITO_10_9(String ESITO_10_9);

	/**
	 * Returns the e s i t o_10_10 of this form_di_segnalazione.
	 *
	 * @return the e s i t o_10_10 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getESITO_10_10();

	/**
	 * Sets the e s i t o_10_10 of this form_di_segnalazione.
	 *
	 * @param ESITO_10_10 the e s i t o_10_10 of this form_di_segnalazione
	 */
	public void setESITO_10_10(String ESITO_10_10);

	/**
	 * Returns the a z i o n i_11 of this form_di_segnalazione.
	 *
	 * @return the a z i o n i_11 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getAZIONI_11();

	/**
	 * Sets the a z i o n i_11 of this form_di_segnalazione.
	 *
	 * @param AZIONI_11 the a z i o n i_11 of this form_di_segnalazione
	 */
	public void setAZIONI_11(String AZIONI_11);

	/**
	 * Returns the f a r m a c o_12_a of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a();

	/**
	 * Sets the f a r m a c o_12_a of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a the f a r m a c o_12_a of this form_di_segnalazione
	 */
	public void setFARMACO_12_a(String FARMACO_12_a);

	/**
	 * Returns the f a r m a c o_12_a_13 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_13 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_13();

	/**
	 * Sets the f a r m a c o_12_a_13 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_13 the f a r m a c o_12_a_13 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_13(String FARMACO_12_a_13);

	/**
	 * Returns the f a r m a c o_12_a_14 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_14 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_14();

	/**
	 * Sets the f a r m a c o_12_a_14 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_14 the f a r m a c o_12_a_14 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_14(String FARMACO_12_a_14);

	/**
	 * Returns the f a r m a c o_12_a_15 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_15 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_15();

	/**
	 * Sets the f a r m a c o_12_a_15 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_15 the f a r m a c o_12_a_15 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_15(String FARMACO_12_a_15);

	/**
	 * Returns the f a r m a c o_12_a_16_1 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_16_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_16_1();

	/**
	 * Sets the f a r m a c o_12_a_16_1 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_16_1 the f a r m a c o_12_a_16_1 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_16_1(String FARMACO_12_a_16_1);

	/**
	 * Returns the f a r m a c o_12_a_16_2 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_16_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_16_2();

	/**
	 * Sets the f a r m a c o_12_a_16_2 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_16_2 the f a r m a c o_12_a_16_2 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_16_2(String FARMACO_12_a_16_2);

	/**
	 * Returns the f a r m a c o_12_a_17 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_17 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_17();

	/**
	 * Sets the f a r m a c o_12_a_17 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_17 the f a r m a c o_12_a_17 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_17(String FARMACO_12_a_17);

	/**
	 * Returns the f a r m a c o_12_a_18 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_18 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_18();

	/**
	 * Sets the f a r m a c o_12_a_18 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_18 the f a r m a c o_12_a_18 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_18(String FARMACO_12_a_18);

	/**
	 * Returns the f a r m a c o_12_a_19 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_19 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_19();

	/**
	 * Sets the f a r m a c o_12_a_19 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_19 the f a r m a c o_12_a_19 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_19(String FARMACO_12_a_19);

	/**
	 * Returns the f a r m a c o_12_a_20 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_a_20 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_a_20();

	/**
	 * Sets the f a r m a c o_12_a_20 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_a_20 the f a r m a c o_12_a_20 of this form_di_segnalazione
	 */
	public void setFARMACO_12_a_20(String FARMACO_12_a_20);

	/**
	 * Returns the f a r m a c o_12_b of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b();

	/**
	 * Sets the f a r m a c o_12_b of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b the f a r m a c o_12_b of this form_di_segnalazione
	 */
	public void setFARMACO_12_b(String FARMACO_12_b);

	/**
	 * Returns the f a r m a c o_12_b_13 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_13 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_13();

	/**
	 * Sets the f a r m a c o_12_b_13 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_13 the f a r m a c o_12_b_13 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_13(String FARMACO_12_b_13);

	/**
	 * Returns the f a r m a c o_12_b_14 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_14 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_14();

	/**
	 * Sets the f a r m a c o_12_b_14 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_14 the f a r m a c o_12_b_14 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_14(String FARMACO_12_b_14);

	/**
	 * Returns the f a r m a c o_12_b_15 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_15 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_15();

	/**
	 * Sets the f a r m a c o_12_b_15 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_15 the f a r m a c o_12_b_15 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_15(String FARMACO_12_b_15);

	/**
	 * Returns the f a r m a c o_12_b_16_1 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_16_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_16_1();

	/**
	 * Sets the f a r m a c o_12_b_16_1 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_16_1 the f a r m a c o_12_b_16_1 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_16_1(String FARMACO_12_b_16_1);

	/**
	 * Returns the f a r m a c o_12_b_16_2 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_16_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_16_2();

	/**
	 * Sets the f a r m a c o_12_b_16_2 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_16_2 the f a r m a c o_12_b_16_2 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_16_2(String FARMACO_12_b_16_2);

	/**
	 * Returns the f a r m a c o_12_b_17 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_17 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_17();

	/**
	 * Sets the f a r m a c o_12_b_17 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_17 the f a r m a c o_12_b_17 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_17(String FARMACO_12_b_17);

	/**
	 * Returns the f a r m a c o_12_b_18 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_18 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_18();

	/**
	 * Sets the f a r m a c o_12_b_18 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_18 the f a r m a c o_12_b_18 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_18(String FARMACO_12_b_18);

	/**
	 * Returns the f a r m a c o_12_b_19 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_19 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_19();

	/**
	 * Sets the f a r m a c o_12_b_19 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_19 the f a r m a c o_12_b_19 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_19(String FARMACO_12_b_19);

	/**
	 * Returns the f a r m a c o_12_b_20 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_b_20 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_b_20();

	/**
	 * Sets the f a r m a c o_12_b_20 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_b_20 the f a r m a c o_12_b_20 of this form_di_segnalazione
	 */
	public void setFARMACO_12_b_20(String FARMACO_12_b_20);

	/**
	 * Returns the f a r m a c o_12_c of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c();

	/**
	 * Sets the f a r m a c o_12_c of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c the f a r m a c o_12_c of this form_di_segnalazione
	 */
	public void setFARMACO_12_c(String FARMACO_12_c);

	/**
	 * Returns the f a r m a c o_12_c_13 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_13 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_13();

	/**
	 * Sets the f a r m a c o_12_c_13 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_13 the f a r m a c o_12_c_13 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_13(String FARMACO_12_c_13);

	/**
	 * Returns the f a r m a c o_12_c_14 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_14 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_14();

	/**
	 * Sets the f a r m a c o_12_c_14 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_14 the f a r m a c o_12_c_14 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_14(String FARMACO_12_c_14);

	/**
	 * Returns the f a r m a c o_12_c_15 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_15 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_15();

	/**
	 * Sets the f a r m a c o_12_c_15 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_15 the f a r m a c o_12_c_15 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_15(String FARMACO_12_c_15);

	/**
	 * Returns the f a r m a c o_12_c_16_1 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_16_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_16_1();

	/**
	 * Sets the f a r m a c o_12_c_16_1 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_16_1 the f a r m a c o_12_c_16_1 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_16_1(String FARMACO_12_c_16_1);

	/**
	 * Returns the f a r m a c o_12_c_16_2 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_16_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_16_2();

	/**
	 * Sets the f a r m a c o_12_c_16_2 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_16_2 the f a r m a c o_12_c_16_2 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_16_2(String FARMACO_12_c_16_2);

	/**
	 * Returns the f a r m a c o_12_c_17 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_17 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_17();

	/**
	 * Sets the f a r m a c o_12_c_17 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_17 the f a r m a c o_12_c_17 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_17(String FARMACO_12_c_17);

	/**
	 * Returns the f a r m a c o_12_c_18 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_18 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_18();

	/**
	 * Sets the f a r m a c o_12_c_18 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_18 the f a r m a c o_12_c_18 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_18(String FARMACO_12_c_18);

	/**
	 * Returns the f a r m a c o_12_c_19 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_19 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_19();

	/**
	 * Sets the f a r m a c o_12_c_19 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_19 the f a r m a c o_12_c_19 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_19(String FARMACO_12_c_19);

	/**
	 * Returns the f a r m a c o_12_c_20 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_12_c_20 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_12_c_20();

	/**
	 * Sets the f a r m a c o_12_c_20 of this form_di_segnalazione.
	 *
	 * @param FARMACO_12_c_20 the f a r m a c o_12_c_20 of this form_di_segnalazione
	 */
	public void setFARMACO_12_c_20(String FARMACO_12_c_20);

	/**
	 * Returns the i n d i c a z i o n i_21_a of this form_di_segnalazione.
	 *
	 * @return the i n d i c a z i o n i_21_a of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICAZIONI_21_a();

	/**
	 * Sets the i n d i c a z i o n i_21_a of this form_di_segnalazione.
	 *
	 * @param INDICAZIONI_21_a the i n d i c a z i o n i_21_a of this form_di_segnalazione
	 */
	public void setINDICAZIONI_21_a(String INDICAZIONI_21_a);

	/**
	 * Returns the i n d i c a z i o n i_21_b of this form_di_segnalazione.
	 *
	 * @return the i n d i c a z i o n i_21_b of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICAZIONI_21_b();

	/**
	 * Sets the i n d i c a z i o n i_21_b of this form_di_segnalazione.
	 *
	 * @param INDICAZIONI_21_b the i n d i c a z i o n i_21_b of this form_di_segnalazione
	 */
	public void setINDICAZIONI_21_b(String INDICAZIONI_21_b);

	/**
	 * Returns the i n d i c a z i o n i_21_c of this form_di_segnalazione.
	 *
	 * @return the i n d i c a z i o n i_21_c of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICAZIONI_21_c();

	/**
	 * Sets the i n d i c a z i o n i_21_c of this form_di_segnalazione.
	 *
	 * @param INDICAZIONI_21_c the i n d i c a z i o n i_21_c of this form_di_segnalazione
	 */
	public void setINDICAZIONI_21_c(String INDICAZIONI_21_c);

	/**
	 * Returns the f a r m a c o_22_a of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a();

	/**
	 * Sets the f a r m a c o_22_a of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a the f a r m a c o_22_a of this form_di_segnalazione
	 */
	public void setFARMACO_22_a(String FARMACO_22_a);

	/**
	 * Returns the f a r m a c o_22_a_23 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_23 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_23();

	/**
	 * Sets the f a r m a c o_22_a_23 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_23 the f a r m a c o_22_a_23 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_23(String FARMACO_22_a_23);

	/**
	 * Returns the f a r m a c o_22_a_24 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_24 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_24();

	/**
	 * Sets the f a r m a c o_22_a_24 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_24 the f a r m a c o_22_a_24 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_24(String FARMACO_22_a_24);

	/**
	 * Returns the f a r m a c o_22_a_25 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_25 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_25();

	/**
	 * Sets the f a r m a c o_22_a_25 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_25 the f a r m a c o_22_a_25 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_25(String FARMACO_22_a_25);

	/**
	 * Returns the f a r m a c o_22_a_26_1 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_26_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_26_1();

	/**
	 * Sets the f a r m a c o_22_a_26_1 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_26_1 the f a r m a c o_22_a_26_1 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_26_1(String FARMACO_22_a_26_1);

	/**
	 * Returns the f a r m a c o_22_a_26_2 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_26_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_26_2();

	/**
	 * Sets the f a r m a c o_22_a_26_2 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_26_2 the f a r m a c o_22_a_26_2 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_26_2(String FARMACO_22_a_26_2);

	/**
	 * Returns the f a r m a c o_22_a_27 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_27 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_27();

	/**
	 * Sets the f a r m a c o_22_a_27 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_27 the f a r m a c o_22_a_27 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_27(String FARMACO_22_a_27);

	/**
	 * Returns the f a r m a c o_22_a_28 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_28 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_28();

	/**
	 * Sets the f a r m a c o_22_a_28 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_28 the f a r m a c o_22_a_28 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_28(String FARMACO_22_a_28);

	/**
	 * Returns the f a r m a c o_22_a_29 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_29 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_29();

	/**
	 * Sets the f a r m a c o_22_a_29 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_29 the f a r m a c o_22_a_29 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_29(String FARMACO_22_a_29);

	/**
	 * Returns the f a r m a c o_22_a_30 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_a_30 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_a_30();

	/**
	 * Sets the f a r m a c o_22_a_30 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_a_30 the f a r m a c o_22_a_30 of this form_di_segnalazione
	 */
	public void setFARMACO_22_a_30(String FARMACO_22_a_30);

	/**
	 * Returns the f a r m a c o_22_b of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b();

	/**
	 * Sets the f a r m a c o_22_b of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b the f a r m a c o_22_b of this form_di_segnalazione
	 */
	public void setFARMACO_22_b(String FARMACO_22_b);

	/**
	 * Returns the f a r m a c o_22_b_23 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_23 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_23();

	/**
	 * Sets the f a r m a c o_22_b_23 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_23 the f a r m a c o_22_b_23 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_23(String FARMACO_22_b_23);

	/**
	 * Returns the f a r m a c o_22_b_24 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_24 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_24();

	/**
	 * Sets the f a r m a c o_22_b_24 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_24 the f a r m a c o_22_b_24 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_24(String FARMACO_22_b_24);

	/**
	 * Returns the f a r m a c o_22_b_25 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_25 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_25();

	/**
	 * Sets the f a r m a c o_22_b_25 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_25 the f a r m a c o_22_b_25 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_25(String FARMACO_22_b_25);

	/**
	 * Returns the f a r m a c o_22_b_26_1 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_26_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_26_1();

	/**
	 * Sets the f a r m a c o_22_b_26_1 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_26_1 the f a r m a c o_22_b_26_1 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_26_1(String FARMACO_22_b_26_1);

	/**
	 * Returns the f a r m a c o_22_b_26_2 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_26_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_26_2();

	/**
	 * Sets the f a r m a c o_22_b_26_2 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_26_2 the f a r m a c o_22_b_26_2 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_26_2(String FARMACO_22_b_26_2);

	/**
	 * Returns the f a r m a c o_22_b_27 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_27 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_27();

	/**
	 * Sets the f a r m a c o_22_b_27 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_27 the f a r m a c o_22_b_27 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_27(String FARMACO_22_b_27);

	/**
	 * Returns the f a r m a c o_22_b_28 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_28 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_28();

	/**
	 * Sets the f a r m a c o_22_b_28 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_28 the f a r m a c o_22_b_28 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_28(String FARMACO_22_b_28);

	/**
	 * Returns the f a r m a c o_22_b_29 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_29 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_29();

	/**
	 * Sets the f a r m a c o_22_b_29 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_29 the f a r m a c o_22_b_29 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_29(String FARMACO_22_b_29);

	/**
	 * Returns the f a r m a c o_22_b_30 of this form_di_segnalazione.
	 *
	 * @return the f a r m a c o_22_b_30 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFARMACO_22_b_30();

	/**
	 * Sets the f a r m a c o_22_b_30 of this form_di_segnalazione.
	 *
	 * @param FARMACO_22_b_30 the f a r m a c o_22_b_30 of this form_di_segnalazione
	 */
	public void setFARMACO_22_b_30(String FARMACO_22_b_30);

	/**
	 * Returns the i n d i c a z i o n i_31_a of this form_di_segnalazione.
	 *
	 * @return the i n d i c a z i o n i_31_a of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICAZIONI_31_a();

	/**
	 * Sets the i n d i c a z i o n i_31_a of this form_di_segnalazione.
	 *
	 * @param INDICAZIONI_31_a the i n d i c a z i o n i_31_a of this form_di_segnalazione
	 */
	public void setINDICAZIONI_31_a(String INDICAZIONI_31_a);

	/**
	 * Returns the i n d i c a z i o n i_31_b of this form_di_segnalazione.
	 *
	 * @return the i n d i c a z i o n i_31_b of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICAZIONI_31_b();

	/**
	 * Sets the i n d i c a z i o n i_31_b of this form_di_segnalazione.
	 *
	 * @param INDICAZIONI_31_b the i n d i c a z i o n i_31_b of this form_di_segnalazione
	 */
	public void setINDICAZIONI_31_b(String INDICAZIONI_31_b);

	/**
	 * Returns the u s o_32 of this form_di_segnalazione.
	 *
	 * @return the u s o_32 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getUSO_32();

	/**
	 * Sets the u s o_32 of this form_di_segnalazione.
	 *
	 * @param USO_32 the u s o_32 of this form_di_segnalazione
	 */
	public void setUSO_32(String USO_32);

	/**
	 * Returns the c o n d i z i o n i_33 of this form_di_segnalazione.
	 *
	 * @return the c o n d i z i o n i_33 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getCONDIZIONI_33();

	/**
	 * Sets the c o n d i z i o n i_33 of this form_di_segnalazione.
	 *
	 * @param CONDIZIONI_33 the c o n d i z i o n i_33 of this form_di_segnalazione
	 */
	public void setCONDIZIONI_33(String CONDIZIONI_33);

	/**
	 * Returns the a l t r e_34 of this form_di_segnalazione.
	 *
	 * @return the a l t r e_34 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getALTRE_34();

	/**
	 * Sets the a l t r e_34 of this form_di_segnalazione.
	 *
	 * @param ALTRE_34 the a l t r e_34 of this form_di_segnalazione
	 */
	public void setALTRE_34(String ALTRE_34);

	/**
	 * Returns the i n d i c a r e_35_1 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_35_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_35_1();

	/**
	 * Sets the i n d i c a r e_35_1 of this form_di_segnalazione.
	 *
	 * @param INDICARE_35_1 the i n d i c a r e_35_1 of this form_di_segnalazione
	 */
	public void setINDICARE_35_1(String INDICARE_35_1);

	/**
	 * Returns the i n d i c a r e_35_2 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_35_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_35_2();

	/**
	 * Sets the i n d i c a r e_35_2 of this form_di_segnalazione.
	 *
	 * @param INDICARE_35_2 the i n d i c a r e_35_2 of this form_di_segnalazione
	 */
	public void setINDICARE_35_2(String INDICARE_35_2);

	/**
	 * Returns the i n d i c a r e_35_3 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_35_3 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_35_3();

	/**
	 * Sets the i n d i c a r e_35_3 of this form_di_segnalazione.
	 *
	 * @param INDICARE_35_3 the i n d i c a r e_35_3 of this form_di_segnalazione
	 */
	public void setINDICARE_35_3(String INDICARE_35_3);

	/**
	 * Returns the i n d i c a r e_35_4 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_35_4 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_35_4();

	/**
	 * Sets the i n d i c a r e_35_4 of this form_di_segnalazione.
	 *
	 * @param INDICARE_35_4 the i n d i c a r e_35_4 of this form_di_segnalazione
	 */
	public void setINDICARE_35_4(String INDICARE_35_4);

	/**
	 * Returns the i n d i c a r e_35_5 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_35_5 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_35_5();

	/**
	 * Sets the i n d i c a r e_35_5 of this form_di_segnalazione.
	 *
	 * @param INDICARE_35_5 the i n d i c a r e_35_5 of this form_di_segnalazione
	 */
	public void setINDICARE_35_5(String INDICARE_35_5);

	/**
	 * Returns the i n d i c a r e_35_6 of this form_di_segnalazione.
	 *
	 * @return the i n d i c a r e_35_6 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getINDICARE_35_6();

	/**
	 * Sets the i n d i c a r e_35_6 of this form_di_segnalazione.
	 *
	 * @param INDICARE_35_6 the i n d i c a r e_35_6 of this form_di_segnalazione
	 */
	public void setINDICARE_35_6(String INDICARE_35_6);

	/**
	 * Returns the q u a l i f i c a_36_1 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_1();

	/**
	 * Sets the q u a l i f i c a_36_1 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_1 the q u a l i f i c a_36_1 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_1(String QUALIFICA_36_1);

	/**
	 * Returns the q u a l i f i c a_36_2 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_2();

	/**
	 * Sets the q u a l i f i c a_36_2 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_2 the q u a l i f i c a_36_2 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_2(String QUALIFICA_36_2);

	/**
	 * Returns the q u a l i f i c a_36_3 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_3 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_3();

	/**
	 * Sets the q u a l i f i c a_36_3 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_3 the q u a l i f i c a_36_3 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_3(String QUALIFICA_36_3);

	/**
	 * Returns the q u a l i f i c a_36_4 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_4 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_4();

	/**
	 * Sets the q u a l i f i c a_36_4 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_4 the q u a l i f i c a_36_4 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_4(String QUALIFICA_36_4);

	/**
	 * Returns the q u a l i f i c a_36_5 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_5 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_5();

	/**
	 * Sets the q u a l i f i c a_36_5 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_5 the q u a l i f i c a_36_5 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_5(String QUALIFICA_36_5);

	/**
	 * Returns the q u a l i f i c a_36_6 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_6 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_6();

	/**
	 * Sets the q u a l i f i c a_36_6 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_6 the q u a l i f i c a_36_6 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_6(String QUALIFICA_36_6);

	/**
	 * Returns the q u a l i f i c a_36_7 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_7 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_7();

	/**
	 * Sets the q u a l i f i c a_36_7 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_7 the q u a l i f i c a_36_7 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_7(String QUALIFICA_36_7);

	/**
	 * Returns the q u a l i f i c a_36_8 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_8 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_8();

	/**
	 * Sets the q u a l i f i c a_36_8 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_8 the q u a l i f i c a_36_8 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_8(String QUALIFICA_36_8);

	/**
	 * Returns the q u a l i f i c a_36_9 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_9 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_9();

	/**
	 * Sets the q u a l i f i c a_36_9 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_9 the q u a l i f i c a_36_9 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_9(String QUALIFICA_36_9);

	/**
	 * Returns the q u a l i f i c a_36_10 of this form_di_segnalazione.
	 *
	 * @return the q u a l i f i c a_36_10 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getQUALIFICA_36_10();

	/**
	 * Sets the q u a l i f i c a_36_10 of this form_di_segnalazione.
	 *
	 * @param QUALIFICA_36_10 the q u a l i f i c a_36_10 of this form_di_segnalazione
	 */
	public void setQUALIFICA_36_10(String QUALIFICA_36_10);

	/**
	 * Returns the d a t i_37_1 of this form_di_segnalazione.
	 *
	 * @return the d a t i_37_1 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDATI_37_1();

	/**
	 * Sets the d a t i_37_1 of this form_di_segnalazione.
	 *
	 * @param DATI_37_1 the d a t i_37_1 of this form_di_segnalazione
	 */
	public void setDATI_37_1(String DATI_37_1);

	/**
	 * Returns the d a t i_37_2 of this form_di_segnalazione.
	 *
	 * @return the d a t i_37_2 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDATI_37_2();

	/**
	 * Sets the d a t i_37_2 of this form_di_segnalazione.
	 *
	 * @param DATI_37_2 the d a t i_37_2 of this form_di_segnalazione
	 */
	public void setDATI_37_2(String DATI_37_2);

	/**
	 * Returns the d a t i_37_3 of this form_di_segnalazione.
	 *
	 * @return the d a t i_37_3 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDATI_37_3();

	/**
	 * Sets the d a t i_37_3 of this form_di_segnalazione.
	 *
	 * @param DATI_37_3 the d a t i_37_3 of this form_di_segnalazione
	 */
	public void setDATI_37_3(String DATI_37_3);

	/**
	 * Returns the d a t i_37_4 of this form_di_segnalazione.
	 *
	 * @return the d a t i_37_4 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDATI_37_4();

	/**
	 * Sets the d a t i_37_4 of this form_di_segnalazione.
	 *
	 * @param DATI_37_4 the d a t i_37_4 of this form_di_segnalazione
	 */
	public void setDATI_37_4(String DATI_37_4);

	/**
	 * Returns the a s l_38 of this form_di_segnalazione.
	 *
	 * @return the a s l_38 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getASL_38();

	/**
	 * Sets the a s l_38 of this form_di_segnalazione.
	 *
	 * @param ASL_38 the a s l_38 of this form_di_segnalazione
	 */
	public void setASL_38(String ASL_38);

	/**
	 * Returns the r e g i o n e_39 of this form_di_segnalazione.
	 *
	 * @return the r e g i o n e_39 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getREGIONE_39();

	/**
	 * Sets the r e g i o n e_39 of this form_di_segnalazione.
	 *
	 * @param REGIONE_39 the r e g i o n e_39 of this form_di_segnalazione
	 */
	public void setREGIONE_39(String REGIONE_39);

	/**
	 * Returns the d a t a_40 of this form_di_segnalazione.
	 *
	 * @return the d a t a_40 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getDATA_40();

	/**
	 * Sets the d a t a_40 of this form_di_segnalazione.
	 *
	 * @param DATA_40 the d a t a_40 of this form_di_segnalazione
	 */
	public void setDATA_40(String DATA_40);

	/**
	 * Returns the f i r m a_41 of this form_di_segnalazione.
	 *
	 * @return the f i r m a_41 of this form_di_segnalazione
	 */
	@AutoEscape
	public String getFIRMA_41();

	/**
	 * Sets the f i r m a_41 of this form_di_segnalazione.
	 *
	 * @param FIRMA_41 the f i r m a_41 of this form_di_segnalazione
	 */
	public void setFIRMA_41(String FIRMA_41);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.daffo.form_di_segnalazione.model.form_di_segnalazione form_di_segnalazione);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.daffo.form_di_segnalazione.model.form_di_segnalazione> toCacheModel();

	@Override
	public com.daffo.form_di_segnalazione.model.form_di_segnalazione toEscapedModel();

	@Override
	public com.daffo.form_di_segnalazione.model.form_di_segnalazione toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}