/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.form_di_segnalazione.model.impl;

import com.daffo.form_di_segnalazione.model.form_di_segnalazione;
import com.daffo.form_di_segnalazione.service.form_di_segnalazioneLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the form_di_segnalazione service. Represents a row in the &quot;form_di_segnalazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link form_di_segnalazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see form_di_segnalazioneImpl
 * @see com.daffo.form_di_segnalazione.model.form_di_segnalazione
 * @generated
 */
public abstract class form_di_segnalazioneBaseImpl
	extends form_di_segnalazioneModelImpl implements form_di_segnalazione {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form_di_segnalazione model instance should use the {@link form_di_segnalazione} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			form_di_segnalazioneLocalServiceUtil.addform_di_segnalazione(this);
		}
		else {
			form_di_segnalazioneLocalServiceUtil.updateform_di_segnalazione(this);
		}
	}
}