/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.sample.model.BookedEquipment;
import com.liferay.sample.service.BookedEquipmentLocalServiceUtil;

/**
 * The extended model base implementation for the BookedEquipment service. Represents a row in the &quot;bookedequipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookedEquipmentImpl}.
 * </p>
 *
 * @author Naveen Kumar
 * @see BookedEquipmentImpl
 * @see com.liferay.sample.model.BookedEquipment
 * @generated
 */
public abstract class BookedEquipmentBaseImpl extends BookedEquipmentModelImpl
	implements BookedEquipment {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a booked equipment model instance should use the {@link BookedEquipment} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BookedEquipmentLocalServiceUtil.addBookedEquipment(this);
		}
		else {
			BookedEquipmentLocalServiceUtil.updateBookedEquipment(this);
		}
	}
}