/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.sample.model.suiluppo_course;
import com.liferay.sample.service.suiluppo_courseLocalServiceUtil;

/**
 * The extended model base implementation for the suiluppo_course service. Represents a row in the &quot;suiluppo_course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link suiluppo_courseImpl}.
 * </p>
 *
 * @author Naveen Kumar
 * @see suiluppo_courseImpl
 * @see com.liferay.sample.model.suiluppo_course
 * @generated
 */
public abstract class suiluppo_courseBaseImpl extends suiluppo_courseModelImpl
	implements suiluppo_course {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a suiluppo_course model instance should use the {@link suiluppo_course} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			suiluppo_courseLocalServiceUtil.addsuiluppo_course(this);
		}
		else {
			suiluppo_courseLocalServiceUtil.updatesuiluppo_course(this);
		}
	}
}