/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.sample.model.suiluppo_application;
import com.liferay.sample.model.suiluppo_applicationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the suiluppo_application service. Represents a row in the &quot;suiluppo_application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.sample.model.suiluppo_applicationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link suiluppo_applicationImpl}.
 * </p>
 *
 * @author Naveen Kumar
 * @see suiluppo_applicationImpl
 * @see com.liferay.sample.model.suiluppo_application
 * @see com.liferay.sample.model.suiluppo_applicationModel
 * @generated
 */
public class suiluppo_applicationModelImpl extends BaseModelImpl<suiluppo_application>
	implements suiluppo_applicationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a suiluppo_application model instance should use the {@link com.liferay.sample.model.suiluppo_application} interface instead.
	 */
	public static final String TABLE_NAME = "suiluppo_application";
	public static final Object[][] TABLE_COLUMNS = {
			{ "applicat_id", Types.BIGINT },
			{ "applicat_name", Types.VARCHAR },
			{ "applicat_email", Types.VARCHAR },
			{ "applicat_phone", Types.VARCHAR },
			{ "course_id", Types.BIGINT },
			{ "applicat_confirm", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table suiluppo_application (applicat_id LONG not null primary key,applicat_name VARCHAR(75) null,applicat_email VARCHAR(75) null,applicat_phone VARCHAR(75) null,course_id LONG,applicat_confirm VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table suiluppo_application";
	public static final String ORDER_BY_JPQL = " ORDER BY suiluppo_application.applicat_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY suiluppo_application.applicat_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.sample.model.suiluppo_application"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.sample.model.suiluppo_application"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.sample.model.suiluppo_application"),
			true);
	public static long COURSE_ID_COLUMN_BITMASK = 1L;
	public static long APPLICAT_ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.sample.model.suiluppo_application"));

	public suiluppo_applicationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _applicat_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setApplicat_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _applicat_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return suiluppo_application.class;
	}

	@Override
	public String getModelClassName() {
		return suiluppo_application.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("applicat_id", getApplicat_id());
		attributes.put("applicat_name", getApplicat_name());
		attributes.put("applicat_email", getApplicat_email());
		attributes.put("applicat_phone", getApplicat_phone());
		attributes.put("course_id", getCourse_id());
		attributes.put("applicat_confirm", getApplicat_confirm());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long applicat_id = (Long)attributes.get("applicat_id");

		if (applicat_id != null) {
			setApplicat_id(applicat_id);
		}

		String applicat_name = (String)attributes.get("applicat_name");

		if (applicat_name != null) {
			setApplicat_name(applicat_name);
		}

		String applicat_email = (String)attributes.get("applicat_email");

		if (applicat_email != null) {
			setApplicat_email(applicat_email);
		}

		String applicat_phone = (String)attributes.get("applicat_phone");

		if (applicat_phone != null) {
			setApplicat_phone(applicat_phone);
		}

		Long course_id = (Long)attributes.get("course_id");

		if (course_id != null) {
			setCourse_id(course_id);
		}

		String applicat_confirm = (String)attributes.get("applicat_confirm");

		if (applicat_confirm != null) {
			setApplicat_confirm(applicat_confirm);
		}
	}

	@Override
	public long getApplicat_id() {
		return _applicat_id;
	}

	@Override
	public void setApplicat_id(long applicat_id) {
		_applicat_id = applicat_id;
	}

	@Override
	public String getApplicat_name() {
		if (_applicat_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicat_name;
		}
	}

	@Override
	public void setApplicat_name(String applicat_name) {
		_applicat_name = applicat_name;
	}

	@Override
	public String getApplicat_email() {
		if (_applicat_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicat_email;
		}
	}

	@Override
	public void setApplicat_email(String applicat_email) {
		_applicat_email = applicat_email;
	}

	@Override
	public String getApplicat_phone() {
		if (_applicat_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicat_phone;
		}
	}

	@Override
	public void setApplicat_phone(String applicat_phone) {
		_applicat_phone = applicat_phone;
	}

	@Override
	public long getCourse_id() {
		return _course_id;
	}

	@Override
	public void setCourse_id(long course_id) {
		_columnBitmask |= COURSE_ID_COLUMN_BITMASK;

		if (!_setOriginalCourse_id) {
			_setOriginalCourse_id = true;

			_originalCourse_id = _course_id;
		}

		_course_id = course_id;
	}

	public long getOriginalCourse_id() {
		return _originalCourse_id;
	}

	@Override
	public String getApplicat_confirm() {
		if (_applicat_confirm == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicat_confirm;
		}
	}

	@Override
	public void setApplicat_confirm(String applicat_confirm) {
		_applicat_confirm = applicat_confirm;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			suiluppo_application.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public suiluppo_application toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (suiluppo_application)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		suiluppo_applicationImpl suiluppo_applicationImpl = new suiluppo_applicationImpl();

		suiluppo_applicationImpl.setApplicat_id(getApplicat_id());
		suiluppo_applicationImpl.setApplicat_name(getApplicat_name());
		suiluppo_applicationImpl.setApplicat_email(getApplicat_email());
		suiluppo_applicationImpl.setApplicat_phone(getApplicat_phone());
		suiluppo_applicationImpl.setCourse_id(getCourse_id());
		suiluppo_applicationImpl.setApplicat_confirm(getApplicat_confirm());

		suiluppo_applicationImpl.resetOriginalValues();

		return suiluppo_applicationImpl;
	}

	@Override
	public int compareTo(suiluppo_application suiluppo_application) {
		long primaryKey = suiluppo_application.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof suiluppo_application)) {
			return false;
		}

		suiluppo_application suiluppo_application = (suiluppo_application)obj;

		long primaryKey = suiluppo_application.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		suiluppo_applicationModelImpl suiluppo_applicationModelImpl = this;

		suiluppo_applicationModelImpl._originalCourse_id = suiluppo_applicationModelImpl._course_id;

		suiluppo_applicationModelImpl._setOriginalCourse_id = false;

		suiluppo_applicationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<suiluppo_application> toCacheModel() {
		suiluppo_applicationCacheModel suiluppo_applicationCacheModel = new suiluppo_applicationCacheModel();

		suiluppo_applicationCacheModel.applicat_id = getApplicat_id();

		suiluppo_applicationCacheModel.applicat_name = getApplicat_name();

		String applicat_name = suiluppo_applicationCacheModel.applicat_name;

		if ((applicat_name != null) && (applicat_name.length() == 0)) {
			suiluppo_applicationCacheModel.applicat_name = null;
		}

		suiluppo_applicationCacheModel.applicat_email = getApplicat_email();

		String applicat_email = suiluppo_applicationCacheModel.applicat_email;

		if ((applicat_email != null) && (applicat_email.length() == 0)) {
			suiluppo_applicationCacheModel.applicat_email = null;
		}

		suiluppo_applicationCacheModel.applicat_phone = getApplicat_phone();

		String applicat_phone = suiluppo_applicationCacheModel.applicat_phone;

		if ((applicat_phone != null) && (applicat_phone.length() == 0)) {
			suiluppo_applicationCacheModel.applicat_phone = null;
		}

		suiluppo_applicationCacheModel.course_id = getCourse_id();

		suiluppo_applicationCacheModel.applicat_confirm = getApplicat_confirm();

		String applicat_confirm = suiluppo_applicationCacheModel.applicat_confirm;

		if ((applicat_confirm != null) && (applicat_confirm.length() == 0)) {
			suiluppo_applicationCacheModel.applicat_confirm = null;
		}

		return suiluppo_applicationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{applicat_id=");
		sb.append(getApplicat_id());
		sb.append(", applicat_name=");
		sb.append(getApplicat_name());
		sb.append(", applicat_email=");
		sb.append(getApplicat_email());
		sb.append(", applicat_phone=");
		sb.append(getApplicat_phone());
		sb.append(", course_id=");
		sb.append(getCourse_id());
		sb.append(", applicat_confirm=");
		sb.append(getApplicat_confirm());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.sample.model.suiluppo_application");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>applicat_id</column-name><column-value><![CDATA[");
		sb.append(getApplicat_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicat_name</column-name><column-value><![CDATA[");
		sb.append(getApplicat_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicat_email</column-name><column-value><![CDATA[");
		sb.append(getApplicat_email());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicat_phone</column-name><column-value><![CDATA[");
		sb.append(getApplicat_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>course_id</column-name><column-value><![CDATA[");
		sb.append(getCourse_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicat_confirm</column-name><column-value><![CDATA[");
		sb.append(getApplicat_confirm());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = suiluppo_application.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			suiluppo_application.class
		};
	private long _applicat_id;
	private String _applicat_name;
	private String _applicat_email;
	private String _applicat_phone;
	private long _course_id;
	private long _originalCourse_id;
	private boolean _setOriginalCourse_id;
	private String _applicat_confirm;
	private long _columnBitmask;
	private suiluppo_application _escapedModel;
}