create table telephonic (
	telephonicId LONG not null primary key,
	Tipo VARCHAR(75) null,
	tipoSede VARCHAR(75) null,
	comuneSede VARCHAR(75) null,
	descrizioneSede VARCHAR(75) null,
	interno VARCHAR(75) null,
	piano VARCHAR(75) null,
	area VARCHAR(75) null,
	blocco VARCHAR(75) null,
	stanza VARCHAR(75) null,
	marca VARCHAR(75) null,
	modello VARCHAR(75) null,
	inventarioSN VARCHAR(75) null,
	unitaOperativa VARCHAR(75) null,
	descrizione VARCHAR(75) null,
	nome VARCHAR(75) null,
	note VARCHAR(75) null,
	visibile VARCHAR(75) null
);