/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the suiluppo_course service. Represents a row in the &quot;suiluppo_course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.suiluppo_courseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.suiluppo_courseImpl}.
 * </p>
 *
 * @author Naveen Kumar
 * @see suiluppo_course
 * @see com.liferay.sample.model.impl.suiluppo_courseImpl
 * @see com.liferay.sample.model.impl.suiluppo_courseModelImpl
 * @generated
 */
public interface suiluppo_courseModel extends BaseModel<suiluppo_course> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a suiluppo_course model instance should use the {@link suiluppo_course} interface instead.
	 */

	/**
	 * Returns the primary key of this suiluppo_course.
	 *
	 * @return the primary key of this suiluppo_course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this suiluppo_course.
	 *
	 * @param primaryKey the primary key of this suiluppo_course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course_id of this suiluppo_course.
	 *
	 * @return the course_id of this suiluppo_course
	 */
	public long getCourse_id();

	/**
	 * Sets the course_id of this suiluppo_course.
	 *
	 * @param course_id the course_id of this suiluppo_course
	 */
	public void setCourse_id(long course_id);

	/**
	 * Returns the docente of this suiluppo_course.
	 *
	 * @return the docente of this suiluppo_course
	 */
	@AutoEscape
	public String getDocente();

	/**
	 * Sets the docente of this suiluppo_course.
	 *
	 * @param Docente the docente of this suiluppo_course
	 */
	public void setDocente(String Docente);

	/**
	 * Returns the evento_ progetto of this suiluppo_course.
	 *
	 * @return the evento_ progetto of this suiluppo_course
	 */
	@AutoEscape
	public String getEvento_Progetto();

	/**
	 * Sets the evento_ progetto of this suiluppo_course.
	 *
	 * @param Evento_Progetto the evento_ progetto of this suiluppo_course
	 */
	public void setEvento_Progetto(String Evento_Progetto);

	/**
	 * Returns the titolo of this suiluppo_course.
	 *
	 * @return the titolo of this suiluppo_course
	 */
	@AutoEscape
	public String getTitolo();

	/**
	 * Sets the titolo of this suiluppo_course.
	 *
	 * @param Titolo the titolo of this suiluppo_course
	 */
	public void setTitolo(String Titolo);

	/**
	 * Returns the descrizione of this suiluppo_course.
	 *
	 * @return the descrizione of this suiluppo_course
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this suiluppo_course.
	 *
	 * @param Descrizione the descrizione of this suiluppo_course
	 */
	public void setDescrizione(String Descrizione);

	/**
	 * Returns the figure_ professionali_ coinvolte of this suiluppo_course.
	 *
	 * @return the figure_ professionali_ coinvolte of this suiluppo_course
	 */
	@AutoEscape
	public String getFigure_Professionali_Coinvolte();

	/**
	 * Sets the figure_ professionali_ coinvolte of this suiluppo_course.
	 *
	 * @param Figure_Professionali_Coinvolte the figure_ professionali_ coinvolte of this suiluppo_course
	 */
	public void setFigure_Professionali_Coinvolte(
		String Figure_Professionali_Coinvolte);

	/**
	 * Returns the data_ inizio of this suiluppo_course.
	 *
	 * @return the data_ inizio of this suiluppo_course
	 */
	@AutoEscape
	public String getData_Inizio();

	/**
	 * Sets the data_ inizio of this suiluppo_course.
	 *
	 * @param Data_Inizio the data_ inizio of this suiluppo_course
	 */
	public void setData_Inizio(String Data_Inizio);

	/**
	 * Returns the data_ fine of this suiluppo_course.
	 *
	 * @return the data_ fine of this suiluppo_course
	 */
	@AutoEscape
	public String getData_Fine();

	/**
	 * Sets the data_ fine of this suiluppo_course.
	 *
	 * @param Data_Fine the data_ fine of this suiluppo_course
	 */
	public void setData_Fine(String Data_Fine);

	/**
	 * Returns the tot_ ore of this suiluppo_course.
	 *
	 * @return the tot_ ore of this suiluppo_course
	 */
	@AutoEscape
	public String getTot_Ore();

	/**
	 * Sets the tot_ ore of this suiluppo_course.
	 *
	 * @param Tot_Ore the tot_ ore of this suiluppo_course
	 */
	public void setTot_Ore(String Tot_Ore);

	/**
	 * Returns the nr_ edizione of this suiluppo_course.
	 *
	 * @return the nr_ edizione of this suiluppo_course
	 */
	@AutoEscape
	public String getNr_Edizione();

	/**
	 * Sets the nr_ edizione of this suiluppo_course.
	 *
	 * @param Nr_Edizione the nr_ edizione of this suiluppo_course
	 */
	public void setNr_Edizione(String Nr_Edizione);

	/**
	 * Returns the sede of this suiluppo_course.
	 *
	 * @return the sede of this suiluppo_course
	 */
	@AutoEscape
	public String getSede();

	/**
	 * Sets the sede of this suiluppo_course.
	 *
	 * @param Sede the sede of this suiluppo_course
	 */
	public void setSede(String Sede);

	/**
	 * Returns the abstract of this suiluppo_course.
	 *
	 * @return the abstract of this suiluppo_course
	 */
	@AutoEscape
	public String getAbstract();

	/**
	 * Sets the abstract of this suiluppo_course.
	 *
	 * @param Abstract the abstract of this suiluppo_course
	 */
	public void setAbstract(String Abstract);

	/**
	 * Returns the dispensa_corso of this suiluppo_course.
	 *
	 * @return the dispensa_corso of this suiluppo_course
	 */
	@AutoEscape
	public String getDispensa_corso();

	/**
	 * Sets the dispensa_corso of this suiluppo_course.
	 *
	 * @param Dispensa_corso the dispensa_corso of this suiluppo_course
	 */
	public void setDispensa_corso(String Dispensa_corso);

	/**
	 * Returns the ammessi_al_corso of this suiluppo_course.
	 *
	 * @return the ammessi_al_corso of this suiluppo_course
	 */
	public long getAmmessi_al_corso();

	/**
	 * Sets the ammessi_al_corso of this suiluppo_course.
	 *
	 * @param Ammessi_al_corso the ammessi_al_corso of this suiluppo_course
	 */
	public void setAmmessi_al_corso(long Ammessi_al_corso);

	/**
	 * Returns the scadenza_ iscrizioni of this suiluppo_course.
	 *
	 * @return the scadenza_ iscrizioni of this suiluppo_course
	 */
	@AutoEscape
	public String getScadenza_Iscrizioni();

	/**
	 * Sets the scadenza_ iscrizioni of this suiluppo_course.
	 *
	 * @param Scadenza_Iscrizioni the scadenza_ iscrizioni of this suiluppo_course
	 */
	public void setScadenza_Iscrizioni(String Scadenza_Iscrizioni);

	/**
	 * Returns the visibile of this suiluppo_course.
	 *
	 * @return the visibile of this suiluppo_course
	 */
	@AutoEscape
	public String getVisibile();

	/**
	 * Sets the visibile of this suiluppo_course.
	 *
	 * @param Visibile the visibile of this suiluppo_course
	 */
	public void setVisibile(String Visibile);

	/**
	 * Returns the bloccato of this suiluppo_course.
	 *
	 * @return the bloccato of this suiluppo_course
	 */
	@AutoEscape
	public String getBloccato();

	/**
	 * Sets the bloccato of this suiluppo_course.
	 *
	 * @param Bloccato the bloccato of this suiluppo_course
	 */
	public void setBloccato(String Bloccato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.sample.model.suiluppo_course suiluppo_course);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.suiluppo_course> toCacheModel();

	@Override
	public com.liferay.sample.model.suiluppo_course toEscapedModel();

	@Override
	public com.liferay.sample.model.suiluppo_course toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}