/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.daffo.model.impl;

import com.liferay.daffo.model.News_Blogs;
import com.liferay.daffo.service.News_BlogsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the News_Blogs service. Represents a row in the &quot;News_Blogs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link News_BlogsImpl}.
 * </p>
 *
 * @author Naveen Kumar
 * @see News_BlogsImpl
 * @see com.liferay.daffo.model.News_Blogs
 * @generated
 */
public abstract class News_BlogsBaseImpl extends News_BlogsModelImpl
	implements News_Blogs {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news_ blogs model instance should use the {@link News_Blogs} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			News_BlogsLocalServiceUtil.addNews_Blogs(this);
		}
		else {
			News_BlogsLocalServiceUtil.updateNews_Blogs(this);
		}
	}
}