/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Telephonic service. Represents a row in the &quot;telephonic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.TelephonicModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.TelephonicImpl}.
 * </p>
 *
 * @author Administrator
 * @see Telephonic
 * @see com.liferay.sample.model.impl.TelephonicImpl
 * @see com.liferay.sample.model.impl.TelephonicModelImpl
 * @generated
 */
public interface TelephonicModel extends BaseModel<Telephonic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a telephonic model instance should use the {@link Telephonic} interface instead.
	 */

	/**
	 * Returns the primary key of this telephonic.
	 *
	 * @return the primary key of this telephonic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this telephonic.
	 *
	 * @param primaryKey the primary key of this telephonic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the telephonic ID of this telephonic.
	 *
	 * @return the telephonic ID of this telephonic
	 */
	public long getTelephonicId();

	/**
	 * Sets the telephonic ID of this telephonic.
	 *
	 * @param telephonicId the telephonic ID of this telephonic
	 */
	public void setTelephonicId(long telephonicId);

	/**
	 * Returns the tipo of this telephonic.
	 *
	 * @return the tipo of this telephonic
	 */
	@AutoEscape
	public String getTipo();

	/**
	 * Sets the tipo of this telephonic.
	 *
	 * @param Tipo the tipo of this telephonic
	 */
	public void setTipo(String Tipo);

	/**
	 * Returns the tipo sede of this telephonic.
	 *
	 * @return the tipo sede of this telephonic
	 */
	@AutoEscape
	public String getTipoSede();

	/**
	 * Sets the tipo sede of this telephonic.
	 *
	 * @param tipoSede the tipo sede of this telephonic
	 */
	public void setTipoSede(String tipoSede);

	/**
	 * Returns the comune sede of this telephonic.
	 *
	 * @return the comune sede of this telephonic
	 */
	@AutoEscape
	public String getComuneSede();

	/**
	 * Sets the comune sede of this telephonic.
	 *
	 * @param comuneSede the comune sede of this telephonic
	 */
	public void setComuneSede(String comuneSede);

	/**
	 * Returns the descrizione sede of this telephonic.
	 *
	 * @return the descrizione sede of this telephonic
	 */
	@AutoEscape
	public String getDescrizioneSede();

	/**
	 * Sets the descrizione sede of this telephonic.
	 *
	 * @param descrizioneSede the descrizione sede of this telephonic
	 */
	public void setDescrizioneSede(String descrizioneSede);

	/**
	 * Returns the interno of this telephonic.
	 *
	 * @return the interno of this telephonic
	 */
	@AutoEscape
	public String getInterno();

	/**
	 * Sets the interno of this telephonic.
	 *
	 * @param interno the interno of this telephonic
	 */
	public void setInterno(String interno);

	/**
	 * Returns the piano of this telephonic.
	 *
	 * @return the piano of this telephonic
	 */
	@AutoEscape
	public String getPiano();

	/**
	 * Sets the piano of this telephonic.
	 *
	 * @param piano the piano of this telephonic
	 */
	public void setPiano(String piano);

	/**
	 * Returns the area of this telephonic.
	 *
	 * @return the area of this telephonic
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this telephonic.
	 *
	 * @param area the area of this telephonic
	 */
	public void setArea(String area);

	/**
	 * Returns the blocco of this telephonic.
	 *
	 * @return the blocco of this telephonic
	 */
	@AutoEscape
	public String getBlocco();

	/**
	 * Sets the blocco of this telephonic.
	 *
	 * @param blocco the blocco of this telephonic
	 */
	public void setBlocco(String blocco);

	/**
	 * Returns the stanza of this telephonic.
	 *
	 * @return the stanza of this telephonic
	 */
	@AutoEscape
	public String getStanza();

	/**
	 * Sets the stanza of this telephonic.
	 *
	 * @param stanza the stanza of this telephonic
	 */
	public void setStanza(String stanza);

	/**
	 * Returns the marca of this telephonic.
	 *
	 * @return the marca of this telephonic
	 */
	@AutoEscape
	public String getMarca();

	/**
	 * Sets the marca of this telephonic.
	 *
	 * @param marca the marca of this telephonic
	 */
	public void setMarca(String marca);

	/**
	 * Returns the modello of this telephonic.
	 *
	 * @return the modello of this telephonic
	 */
	@AutoEscape
	public String getModello();

	/**
	 * Sets the modello of this telephonic.
	 *
	 * @param modello the modello of this telephonic
	 */
	public void setModello(String modello);

	/**
	 * Returns the inventario s n of this telephonic.
	 *
	 * @return the inventario s n of this telephonic
	 */
	@AutoEscape
	public String getInventarioSN();

	/**
	 * Sets the inventario s n of this telephonic.
	 *
	 * @param inventarioSN the inventario s n of this telephonic
	 */
	public void setInventarioSN(String inventarioSN);

	/**
	 * Returns the unita operativa of this telephonic.
	 *
	 * @return the unita operativa of this telephonic
	 */
	@AutoEscape
	public String getUnitaOperativa();

	/**
	 * Sets the unita operativa of this telephonic.
	 *
	 * @param unitaOperativa the unita operativa of this telephonic
	 */
	public void setUnitaOperativa(String unitaOperativa);

	/**
	 * Returns the descrizione of this telephonic.
	 *
	 * @return the descrizione of this telephonic
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this telephonic.
	 *
	 * @param descrizione the descrizione of this telephonic
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the nome of this telephonic.
	 *
	 * @return the nome of this telephonic
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this telephonic.
	 *
	 * @param nome the nome of this telephonic
	 */
	public void setNome(String nome);

	/**
	 * Returns the note of this telephonic.
	 *
	 * @return the note of this telephonic
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this telephonic.
	 *
	 * @param note the note of this telephonic
	 */
	public void setNote(String note);

	/**
	 * Returns the visibile of this telephonic.
	 *
	 * @return the visibile of this telephonic
	 */
	@AutoEscape
	public String getVisibile();

	/**
	 * Sets the visibile of this telephonic.
	 *
	 * @param visibile the visibile of this telephonic
	 */
	public void setVisibile(String visibile);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.sample.model.Telephonic telephonic);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.Telephonic> toCacheModel();

	@Override
	public com.liferay.sample.model.Telephonic toEscapedModel();

	@Override
	public com.liferay.sample.model.Telephonic toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}