/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BookedEquipment service. Represents a row in the &quot;bookedequipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.BookedEquipmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.BookedEquipmentImpl}.
 * </p>
 *
 * @author Naveen Kumar
 * @see BookedEquipment
 * @see com.liferay.sample.model.impl.BookedEquipmentImpl
 * @see com.liferay.sample.model.impl.BookedEquipmentModelImpl
 * @generated
 */
public interface BookedEquipmentModel extends BaseModel<BookedEquipment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a booked equipment model instance should use the {@link BookedEquipment} interface instead.
	 */

	/**
	 * Returns the primary key of this booked equipment.
	 *
	 * @return the primary key of this booked equipment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this booked equipment.
	 *
	 * @param primaryKey the primary key of this booked equipment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the booked_equip_id of this booked equipment.
	 *
	 * @return the booked_equip_id of this booked equipment
	 */
	public long getBooked_equip_id();

	/**
	 * Sets the booked_equip_id of this booked equipment.
	 *
	 * @param booked_equip_id the booked_equip_id of this booked equipment
	 */
	public void setBooked_equip_id(long booked_equip_id);

	/**
	 * Returns the equip_id of this booked equipment.
	 *
	 * @return the equip_id of this booked equipment
	 */
	public long getEquip_id();

	/**
	 * Sets the equip_id of this booked equipment.
	 *
	 * @param equip_id the equip_id of this booked equipment
	 */
	public void setEquip_id(long equip_id);

	/**
	 * Returns the course_id of this booked equipment.
	 *
	 * @return the course_id of this booked equipment
	 */
	public long getCourse_id();

	/**
	 * Sets the course_id of this booked equipment.
	 *
	 * @param course_id the course_id of this booked equipment
	 */
	public void setCourse_id(long course_id);

	/**
	 * Returns the equip_quantity of this booked equipment.
	 *
	 * @return the equip_quantity of this booked equipment
	 */
	public int getEquip_quantity();

	/**
	 * Sets the equip_quantity of this booked equipment.
	 *
	 * @param equip_quantity the equip_quantity of this booked equipment
	 */
	public void setEquip_quantity(int equip_quantity);

	/**
	 * Returns the booked_equip_status of this booked equipment.
	 *
	 * @return the booked_equip_status of this booked equipment
	 */
	public boolean getBooked_equip_status();

	/**
	 * Returns <code>true</code> if this booked equipment is booked_equip_status.
	 *
	 * @return <code>true</code> if this booked equipment is booked_equip_status; <code>false</code> otherwise
	 */
	public boolean isBooked_equip_status();

	/**
	 * Sets whether this booked equipment is booked_equip_status.
	 *
	 * @param booked_equip_status the booked_equip_status of this booked equipment
	 */
	public void setBooked_equip_status(boolean booked_equip_status);

	/**
	 * Returns the booked_equip_date of this booked equipment.
	 *
	 * @return the booked_equip_date of this booked equipment
	 */
	@AutoEscape
	public String getBooked_equip_date();

	/**
	 * Sets the booked_equip_date of this booked equipment.
	 *
	 * @param booked_equip_date the booked_equip_date of this booked equipment
	 */
	public void setBooked_equip_date(String booked_equip_date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.sample.model.BookedEquipment bookedEquipment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.BookedEquipment> toCacheModel();

	@Override
	public com.liferay.sample.model.BookedEquipment toEscapedModel();

	@Override
	public com.liferay.sample.model.BookedEquipment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}