/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the suiluppo_room_allocation_archive service. Represents a row in the &quot;suiluppo_room_allocation_archive&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.suiluppo_room_allocation_archiveModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.suiluppo_room_allocation_archiveImpl}.
 * </p>
 *
 * @author Naveen Kumar
 * @see suiluppo_room_allocation_archive
 * @see com.liferay.sample.model.impl.suiluppo_room_allocation_archiveImpl
 * @see com.liferay.sample.model.impl.suiluppo_room_allocation_archiveModelImpl
 * @generated
 */
public interface suiluppo_room_allocation_archiveModel extends BaseModel<suiluppo_room_allocation_archive> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a suiluppo_room_allocation_archive model instance should use the {@link suiluppo_room_allocation_archive} interface instead.
	 */

	/**
	 * Returns the primary key of this suiluppo_room_allocation_archive.
	 *
	 * @return the primary key of this suiluppo_room_allocation_archive
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this suiluppo_room_allocation_archive.
	 *
	 * @param primaryKey the primary key of this suiluppo_room_allocation_archive
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the room_allocat_archive_id of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_allocat_archive_id of this suiluppo_room_allocation_archive
	 */
	public long getRoom_allocat_archive_id();

	/**
	 * Sets the room_allocat_archive_id of this suiluppo_room_allocation_archive.
	 *
	 * @param room_allocat_archive_id the room_allocat_archive_id of this suiluppo_room_allocation_archive
	 */
	public void setRoom_allocat_archive_id(long room_allocat_archive_id);

	/**
	 * Returns the room i d of this suiluppo_room_allocation_archive.
	 *
	 * @return the room i d of this suiluppo_room_allocation_archive
	 */
	public long getRoomID();

	/**
	 * Sets the room i d of this suiluppo_room_allocation_archive.
	 *
	 * @param roomID the room i d of this suiluppo_room_allocation_archive
	 */
	public void setRoomID(long roomID);

	/**
	 * Returns the course_id of this suiluppo_room_allocation_archive.
	 *
	 * @return the course_id of this suiluppo_room_allocation_archive
	 */
	public long getCourse_id();

	/**
	 * Sets the course_id of this suiluppo_room_allocation_archive.
	 *
	 * @param course_id the course_id of this suiluppo_room_allocation_archive
	 */
	public void setCourse_id(long course_id);

	/**
	 * Returns the room_allocat_date of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_allocat_date of this suiluppo_room_allocation_archive
	 */
	@AutoEscape
	public String getRoom_allocat_date();

	/**
	 * Sets the room_allocat_date of this suiluppo_room_allocation_archive.
	 *
	 * @param room_allocat_date the room_allocat_date of this suiluppo_room_allocation_archive
	 */
	public void setRoom_allocat_date(String room_allocat_date);

	/**
	 * Returns the room_allocat_start time of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_allocat_start time of this suiluppo_room_allocation_archive
	 */
	@AutoEscape
	public String getRoom_allocat_startTime();

	/**
	 * Sets the room_allocat_start time of this suiluppo_room_allocation_archive.
	 *
	 * @param room_allocat_startTime the room_allocat_start time of this suiluppo_room_allocation_archive
	 */
	public void setRoom_allocat_startTime(String room_allocat_startTime);

	/**
	 * Returns the room_allocat_start of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_allocat_start of this suiluppo_room_allocation_archive
	 */
	@AutoEscape
	public String getRoom_allocat_start();

	/**
	 * Sets the room_allocat_start of this suiluppo_room_allocation_archive.
	 *
	 * @param room_allocat_start the room_allocat_start of this suiluppo_room_allocation_archive
	 */
	public void setRoom_allocat_start(String room_allocat_start);

	/**
	 * Returns the room_allocat_end of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_allocat_end of this suiluppo_room_allocation_archive
	 */
	@AutoEscape
	public String getRoom_allocat_end();

	/**
	 * Sets the room_allocat_end of this suiluppo_room_allocation_archive.
	 *
	 * @param room_allocat_end the room_allocat_end of this suiluppo_room_allocation_archive
	 */
	public void setRoom_allocat_end(String room_allocat_end);

	/**
	 * Returns the room_allocat_status of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_allocat_status of this suiluppo_room_allocation_archive
	 */
	@AutoEscape
	public String getRoom_allocat_status();

	/**
	 * Sets the room_allocat_status of this suiluppo_room_allocation_archive.
	 *
	 * @param room_allocat_status the room_allocat_status of this suiluppo_room_allocation_archive
	 */
	public void setRoom_allocat_status(String room_allocat_status);

	/**
	 * Returns the room_allocat_end time of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_allocat_end time of this suiluppo_room_allocation_archive
	 */
	@AutoEscape
	public String getRoom_allocat_endTime();

	/**
	 * Sets the room_allocat_end time of this suiluppo_room_allocation_archive.
	 *
	 * @param room_allocat_endTime the room_allocat_end time of this suiluppo_room_allocation_archive
	 */
	public void setRoom_allocat_endTime(String room_allocat_endTime);

	/**
	 * Returns the room_archive_date of this suiluppo_room_allocation_archive.
	 *
	 * @return the room_archive_date of this suiluppo_room_allocation_archive
	 */
	@AutoEscape
	public String getRoom_archive_date();

	/**
	 * Sets the room_archive_date of this suiluppo_room_allocation_archive.
	 *
	 * @param room_archive_date the room_archive_date of this suiluppo_room_allocation_archive
	 */
	public void setRoom_archive_date(String room_archive_date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.sample.model.suiluppo_room_allocation_archive suiluppo_room_allocation_archive);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.suiluppo_room_allocation_archive> toCacheModel();

	@Override
	public com.liferay.sample.model.suiluppo_room_allocation_archive toEscapedModel();

	@Override
	public com.liferay.sample.model.suiluppo_room_allocation_archive toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}